### ISSUE TITLE
Style buttons

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#11]
There are 3 kinds:

1. Default
2. Outline
3. Square

Used outlines on /what-we-do

I think we should rework them a bit. 

My thoughts right now:

**Default** - should look the most like a "button". Perhaps a 3 dimensional effect - I have something in mind.

**Outline** - a less "button-y" style that can work as a "read more" kinda link. (as on /what-we-do). Maybe just an outline of our random 4-sided polygon/rectangle that we're using on the page titles.

**Square** - matching more the random 4-sided polygon/rectangle style we're using on page titles. With some way of making it clear it's a link.

Something to consider:

If we apply the same polygon style to our headers, we'll need to have some visual differentiation between headers and buttons.

**Comment by slambert** [comment]
Ok, here's some sketches of what I had in mind for the buttons.

![button designs 1600px](https://user-images.githubusercontent.com/67271/62741719-f8041580-ba09-11e9-9923-6f4285d706cd.jpg)

I labeled what I thought could work for *Default, Outline, and Square* and left some other options that we could use if not all these are possible.

Of course, I'd love it if each instance of the button had a bit of randomness for the corners of the polygon and a random, slight rotation of the button, but that can come later if it's possible.
 
Speaking of possible - how possible is this in CSS? Well, I did a little research and found this which may be helpful:

https://stackoverflow.com/questions/31854185/how-to-add-border-in-my-clip-path-polygon-css-style

What do y'all think?

**Comment by zoracreates** [comment]
The problem with using the clip-path property as a solution is that [it's not very well supported](https://caniuse.com/#search=clip-path) outside of newer versions of Firefox, unless we're using some kind of SVG. I am not sure how inserting an SVG for each button would work. Is there a way to do it with PHP @laras126? 

Alternatively, I believe it might be possible to create a similar clip-path effect by playing around with borders and/or pseudo `::before` and `::after` elements. I attempted this with the h2, h3, and h4 on #65 but I need to think a bit more about how it might work.

As for the randomness effect, if we do CSS only, [we'd have to add a few styles](https://css-tricks.com/forums/topic/css3-random-number/#post-80337). I can play around with this, but there are easier ways to do it. There is JavaScript and PHP, but  we can also try something like this custom Sass function to generate a random number:

```
@function randomNum($min, $max) {
  $rand: random();
  $randomNum: $min + floor($rand * (($max - $min) + 1));
  
  @return $randomNum;
}

h3 {
   transform: rotate(#{randomNum(-1.8, 2)}deg);
}
```
I can't take credit for this function, found it on [Stackoverflow](https://stackoverflow.com/questions/41096204/how-to-generate-a-random-number-within-a-min-and-max-parameters-in-sass) and  this [SassMeister demo](https://www.sassmeister.com/gist/56375ccfc15cf7d9f769b6ddc0b33e7f).

**Comment by zoracreates** [comment]
I also meant to mention, my one concern with styling buttons this way is that they look very similar to the h2, h3, and h4 styles. Buttons should be distinguishable enough for usability purposes. While the drop-shadow is a good start, are there other ways we can vary them?

**Comment by slambert** [comment]
I had that thought as I was designing them. Do you have any ideas?

**Comment by slambert** [comment]
right now the differences are: 

- fonts
- "ghost/shadow"

Ok, how about the below?

This way every button has 1) different font, 2) a ghost/shadow, and 3) a clear outline. 

![button designs v2 1600px](https://user-images.githubusercontent.com/67271/62784299-304c3800-ba8c-11e9-9f58-aea66f782235.jpg)

**Comment by slambert** [comment]
We could also make the contrast black, which would make it more obvious, but I'm not sure I like this _as much_.

![button designs v3](https://user-images.githubusercontent.com/67271/62784511-a5b80880-ba8c-11e9-9793-e1c94e9b4913.jpg)

**Comment by laras126** [comment]
@zoracreates I posted this in Slack also, but check this out for a custom property solution for the random corners - could be assigned similar to the c4aa-duotone, and the cascade will ensure each are different: https://codepen.io/laras126/pen/VoGzOd

We should test the speed on this though when there are a few elements – should be okay, but another approach would be to apply the variable values as inlines styles and the random functionality would be in PHP.

**Comment by zoracreates** [comment]
@laras126 I like that solution. Let's try it out. I did fork and tweak a bit. Dropping it here in case you want to take a look: https://codepen.io/zoracreates/pen/RXePNe

@slambert I'm not a huge fan of the black shadow either. Maybe the gray and the fonts are enough distinction. Let's see how it looks on a page.

**Comment by laras126** [comment]
@zoracreates Yesss that's great! Thank you for consolidating my spaghetti code! I think we could potentially add that to `button` (or whatever the button/link selectors are) and drop it in to the theme and see what happens. 

For adding the JS, you can create a folder for JS `js/script.js` in the child theme and add this line to the `c4aa_enqueue_assets` function:

```
wp_enqueue_script( 'c4aa-js', get_stylesheet_directory_uri() . '/js/script.js', array(), '1.0.0', true );
```

**Comment by slambert** [comment]
Let's see what this looks like, but I just remembered – within the design spec we do have a blue and a yellow we can use to highlight things. I rarely use them except in slideshows we create, but those colors are there....

**Comment by slambert** [comment]
@zoracreates this is looking great! I like the animation. 

I realized I got the labels for the buttons wrong above (sorry!)

What I called olid should be what they call "Square"
Default is good.
What I called square should be what they call "Outline"

Sound good?

Also, on hover, the red should probably stay red, or go to a slightly darker shade like #992129 – do you think we can do this without adding another color to the palette? Like by altering the exisiting color with `filter` or something?

And polygon effect. Hopefully that doesn't make it too bonkers.
