### ISSUE TITLE
Add a class for just a plain ol' untreated "color" featured image

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#115]
I realized there may be a scenario where we need to display an image without our treatments - like a special image that was black and white and red and we needed that to show up that way (this came up for me today). Or featuring a graph that becomes confusing when the colors are altered. 

So can we add an optional class that bypasses the treatments for header images and images in the body?

**Comment by laras126** [comment]
@slambert is this only on image blocks or for the header images and archive images too?

**Comment by slambert** [comment]
@laras126 Header images and archive images too.

**Comment by slambert** [comment]
Header images especially. This also means enabling the red banner for the header image also.

**Comment by laras126** [comment]
@slambert Check this one out here - http://backtobasics.c4aa.org/2020/11/test-post-with-no-color-header/

There is a `none` option. This will also not have a filter on the image when it is listed in the archive.

**Comment by slambert** [comment]
![Screen Shot 2020-11-20 at 3 10 14 PM](https://user-images.githubusercontent.com/67271/99845459-b043c780-2b42-11eb-9497-a7f701c3ae5c.png)

That works, but can we add a red or black bar under the text with the author and date?

And I could see putting the red or black color bar behind on the title on something like this as being really helpful.

**Comment by laras126** [comment]
@slambert How is this? 
![Screen Shot 2020-11-20 at 3 40 26 PM](https://user-images.githubusercontent.com/445861/99847906-ceabc200-2b46-11eb-834a-59aa1fb2b322.png)
![Screen Shot 2020-11-20 at 3 40 39 PM](https://user-images.githubusercontent.com/445861/99847911-d1a6b280-2b46-11eb-8ea1-75acfd8f0ba4.png)

**Comment by slambert** [comment]
SO HOT
