### ISSUE TITLE
Clip Paths on headers in master branch have bad margin/padding

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#124]
<img width="936" alt="Screen Shot 2019-09-28 at 11 45 58 AM" src="https://user-images.githubusercontent.com/67271/65819025-af84ff00-e1e5-11e9-898f-b73bf6c9d636.png">

This is on http://backtobasics.c4aa.org/

**Comment by zoracreates** [comment]
@slambert  The new JS function for clipPaths doesn't automatically add the style to all headers and buttons. For the new clipPath classes to apply the headers and buttons need to be added using the editor. I can jump in and do this for all the headers and buttons in master.
<img width="694" alt="Screen Shot 2019-09-28 at 2 51 51 PM" src="https://user-images.githubusercontent.com/29125560/65821137-a56ffa00-e1ff-11e9-91eb-42813f74cf34.png">

This is what I am seeing when I update the existing headers. Let me know if this is not the case for you.
<img width="667" alt="Screen Shot 2019-09-28 at 2 52 30 PM" src="https://user-images.githubusercontent.com/29125560/65821136-a4d76380-e1ff-11e9-8c2b-5f4d861f7955.png">

**Comment by zoracreates** [comment]
@slambert  On #125 I added a style sheet for the clipPath editor blocks, so it is possible to see when the clipPath is applied to a heading or a button. 

<img width="895" alt="Screen Shot 2019-09-28 at 8 56 29 PM" src="https://user-images.githubusercontent.com/29125560/65824185-b71ec500-e232-11e9-9a08-cb7fd551f987.png">

**Comment by slambert** [comment]
The above is helpul. Can the buttons be a closer match to what they look like on the front end? The standard button being blue might throw people off.

**Comment by slambert** [comment]
One more thing related to these headers...

The first letter ended up landing too close to the left, so it's halfway on this photo. I _love_ the overlap of the left edge of the box onto the image, but the text should be a bit more to the right.

<img width="1375" alt="Screen Shot 2019-10-06 at 1 14 55 PM" src="https://user-images.githubusercontent.com/67271/66272735-7ed34400-e83b-11e9-9849-f84ee4fcad8c.png">
