### ISSUE TITLE
Add grid to archive posts

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#13]
Excerpt / title next to image and post meta.

**Comment by laras126** [comment]
@slambert Progress! http://backtobasics.c4aa.org/category/news/

Let me know if you want to restrict the dimensions of the thumbnails – I'm not 100% sure what they are doing at the moment, but it looks reasonable.

**Comment by slambert** [comment]
@zoracreates you're working on this now?

**Comment by slambert** [comment]
@laras126 I don't mind the icons. We can leave them for now. 

The left alignment works for me - is that what you meant?

All the thumbnails look fine to me.

**Comment by slambert** [comment]
Let's call this good for now.
