### ISSUE TITLE
Support image filters in Cover blocks

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#137]

**Comment by laras126** [comment]
@slambert Here is what the current image filters applied to a cover block will look like – https://codepen.io/laras126/pen/Rwwwvjw

Scroll down to the cover block heading and you can click the buttons to change them. We can either apply that – which will be least dev. effort – or create some special case filters for the cover specifically. The CSS for the cover image starts at line 183 if you want to play around with it.

**Comment by slambert** [comment]
@laras126 Ah, so is what you're saying is it won't work the same way as it will for other images?

I think cover blocks could work _one_ way and that would be ok. It'd be so rarely used anyway. 

The options are:

1. having some full color bleed come in
2. having it be entirely black and white via `filter: grayscale(100%) sepia(0%)`
3. ??

If those are the options, I choose 2, we can skip the other options, and we can figure out how to adjust the other filter settings to make it a bit better.
