### ISSUE TITLE
Style post meta / stick to bottom of featured image

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#14]
Style the post meta (.entry-meta) on featured image on single posts and pages as a bar, smaller text, stuck to bottom of the large post header image.

Something like this but nicer looking: 

![Screen Shot 2019-07-29 at 11 55 57 AM](https://user-images.githubusercontent.com/445861/62062931-f5c6dd80-b1f7-11e9-9055-a72ffa7be86e.png)

CSS notes:
* You will need to remove the margin left/right on this: .site-header.featured-image .site-featured-image .entry-header
* on .entry-meta, something like this:
```
position: absolute;
bottom: -55px; // But not hardcoded like this - should stick to bottom
left: 0;
width: 100%;
font-size: 0.75rem; 
background-color: var(--color-brandRed); // Colors could come from duotone variables instead
color: white;
padding: 0.75rem;
```
* Hid the icons - not sure if we would want those or not

**Comment by slambert** [comment]
Assigning this to my self for some final tweaking of the fonts.
