### ISSUE TITLE
Text and Media block: Image 100% + cover

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#15]
on figure:
height: 100%;

on image:
height: 100%;
object-fit: cover;

**Comment by slambert** [comment]
Um... you might hate this. With the Gutenberg plugin, there's some new features that do what we need (and kinda better).

<img width="277" alt="Screen Shot 2019-06-28 at 7 30 24 PM" src="https://user-images.githubusercontent.com/67271/60376228-6ef5c980-99db-11e9-9db6-2c5be4f69256.png">

Should we just roll this back?

**Comment by laras126** [comment]
Ah, indeed - will do!
