### ISSUE TITLE
Make sure lazy loading is working

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#150]

**Comment by slambert** [comment]
#191 Dupe?

And is this relevant anymore? Isn't in WP core now?

**Comment by slambert** [comment]
@laras126 re-open if you think this needs to be tested. I disabled our plugin because it was causing very small images to disappear. But if it's in core now...

**Comment by slambert** [comment]
Nevermind - this is definitely done as per https://github.com/thec4aa/c4aa-org/issues/191
