### ISSUE TITLE
backrgound and text colors selected in block aren't being applied

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#152]
I've added `.has-caa-black-background-color` and `has-caa-biege-color` to a paragraph, but it's not showing up.

I think it's getting to main.css? I can't find any reference to it there.

**Comment by slambert** [comment]
Also seeing this in Media & Text Block

**Comment by slambert** [comment]
Noted that this may be working on pages, but not in posts.

**Comment by laras126** [comment]
should work now!
