### ISSUE TITLE
Columns overlap with block below

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#153]
You can see an example in the image. The content of the column overlaps with the header below. Some kind of "clear" or positioning thing? 

This is on the home page.

<img width="2127" alt="Screen Shot 2019-11-03 at 1 18 59 PM" src="https://user-images.githubusercontent.com/67271/68089980-91419d00-fe3c-11e9-9aef-c4251bb24348.png">

**Comment by laras126** [comment]
For small bug issues, can you always post a link for reference? Checking now

**Comment by laras126** [comment]
Wow, this makes me unhappy with Gutenberg CSS – there some wonky stuff going on in there. Will debug some more later.

**Comment by slambert** [comment]
@laras126 Did we solve this on Friday with this?

https://github.com/thec4aa/c4aa-org/commit/89a8baefeb706112a0a5cf8bb7a1690367ec8264

Or something else?

**Comment by slambert** [comment]
haven't seen this in a long time.
