### ISSUE TITLE
Duotone effects not working on Media & Text Block (or maybe all Pages?)

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#155]
1. Create a Media & Text block
2. Add a color photo
3. Add Additional CSS Class(es): `c4aa-duotone beige-and-grey`

I think it's just not being selected...

**Comment by slambert** [comment]
Also not working on the images here:
http://backtobasics.c4aa.org/what-we-do/

**Comment by laras126** [comment]
We don't need to add the CSS classes anymore (apologies if I didn't communicate that enough) – only choose from the block transform dropdown. It looks like that isn't showing the preview styles now, but it still works on the front-end.

http://backtobasics.c4aa.org/what-we-do/

<img width="452" alt="Screen Shot 2019-11-10 at 9 11 29 AM" src="https://user-images.githubusercontent.com/445861/68545332-25aa8300-039a-11ea-8e81-8ba4a18402d4.png">
