### ISSUE TITLE
image treatments span larger than the image size

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#178]
Can be seen here:

https://c4aa.org/2018/07/amsterdam-2018-creative-action-accelerator-2

<img width="1019" alt="Screen Shot 2019-12-07 at 12 18 05 AM" src="https://user-images.githubusercontent.com/67271/70369428-38c04e00-1887-11ea-8663-bbeb06d3f245.png">

**Comment by laras126** [comment]
Also overlapping the captions! http://backtobasics.c4aa.org/2019/02/phoebe-davies/

**Comment by laras126** [comment]
Something like this on the figcaption - and remove `overflow: hidden` from the `a-filter-child-img` mixin:
```
position: absolute;
bottom: 0;
transform: translateY(100%);
```

**Comment by slambert** [comment]
It appears this is fixed?
