### ISSUE TITLE
Include examples of image treatments in our custom block styles

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#181]
Our image treatments don't get previewed in the editor.

Reference links:

https://make.wordpress.org/core/2019/09/24/new-block-apis-in-wordpress-5-3/

**Comment by slambert** [comment]
This is not really gonna happen right @laras126? Should we close it?

**Comment by laras126** [comment]
It could happen! It's not too complex to do - if you think it's valuable then yes, if not, then close.

**Comment by slambert** [comment]
In the selector, it's maybe not worth the trouble. BUt if we could see it in the editor - oh me oh my, that would be so great.

**Comment by slambert** [comment]
Since the gutenburg duotone stuff, this no longer applies
