### ISSUE TITLE
Add search icon to top menu

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#190]
**Is your feature request related to a problem? Please describe.**
We lack clear, easy access to the search.

**Describe the solution you'd like**
A link to the search page is in the footer. I'd love to add a magnifying class icon 🔍 for a search in the upper menu. So it can be there, but not take up a bunch of space.

**Additional context**
[Maybe more fontawesome style?](https://fontawesome.com/icons/search?style=solid) Or done with SVG?

**Technical Guidance**
- Add a new Custom Link to the 2019Menu (Primary) for "Search" pointed at "/search
- Add a CSS Class to it with a relevant class
- Use that class to visually hide the link text and replace it with a magnifying glass icon

**Definition of Done**
- Search is included in the nav
- the implementation matches the design
- PR is submitted referencing this issue.

**Comment by slambert** [comment]
Looking at stats, search isn't really used. I think if it was more prominent, it may be?

**Comment by andrewheins** [comment]
I feel like there's a possibility this is literally a checkbox in the Appearance Menu that would be a 5 second fix. Otherwise, this is < 1 hour to implement and style.

**Comment by andrewheins** [comment]
Updated to full request.I've checked, and there's no "click to add" option on the 2019 theme.

**Comment by andrewheins** [comment]
@zenbug Would you be interested in taking this on? You're basically just finding space for a search icon, and then directing the user to https://c4aa.org/search as an initial version.

**Comment by zenbug** [comment]
Yes!

**Comment by andrewheins** [comment]
@zenbug Any progress here?

**Comment by zenbug** [comment]
I've been waiting to have the new menu finalized, as that will impact this somewhat, but I will have a look at this today.

**Comment by zenbug** [comment]
Okay I created a pull request for this.

https://github.com/thec4aa/c4aa-org/pull/263

**Comment by slambert** [comment]
This isn't in the mobile menu. Maybe could be done by adding "search" in the menu but turning the visibility off except on mobile.
