### ISSUE TITLE
Lazy loader making small images not show up

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#191]
I saw this in a few places. For smaller images - like 250px or less – the images just wouldn't show up at all.

I turned off the lazy loader, but you can see what I mean if you activate it and look for the first image on this page:

https://c4aa.org/2016/04/ron-goldberg

**Comment by slambert** [comment]
Lazy loader is now incorporated into WordPress core?

**Comment by laras126** [comment]
Images are indeed lazy loading from core, so we can remove the plugin!
