### ISSUE TITLE
Long post titles are cut off on mobile

### ISSUE THREAD

**Issue by laras126** [thec4aa/c4aa-org#204]
Example:

![IMG_E008A6178D81-1](https://user-images.githubusercontent.com/445861/100628908-b8e08e80-32f6-11eb-8292-5845e0f136b3.jpeg)

https://c4aa.org/2020/11/ishtar-lakhani-on-bbc-100-women-list

**Comment by slambert** [comment]
Ah, this happens on desktop too, if the title is tooooooo looooong
