### ISSUE TITLE
Image treatments not working on images without a featured image

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#206]
1. Create a new page.
2. Create a 30/70 column layout.
3. put an image in the left column and apply red and beige style
4. put some text in right column (just cuz)

I'm seeing this:

![Screen Shot 2020-12-02 at 8 08 51 PM](https://user-images.githubusercontent.com/67271/100950527-7ecfe200-34da-11eb-8613-fb04f5b325b5.png)

If you add an image anywhere else on the page, it seems to work - but only when in preview???

![Screen Shot 2020-12-02 at 8 13 57 PM](https://user-images.githubusercontent.com/67271/100950718-f30a8580-34da-11eb-955c-ad0a34e7b53d.png)

On older posts with similar layouts I'm not seeing this issue: https://c4aa.org/about/beka-economopoulos

🤨

**Comment by slambert** [comment]
I'm uploading images into another post and seeing the same problem, but it's not working in preview either. 😕

**Comment by slambert** [comment]
Just figured out it has to do with whether there's a featured image or not.

**Comment by slambert** [comment]
https://c4aa.org/about/merith-basey <-- this was made a while ago and doesn't have the problem. It does happen on new pages.

**Comment by laras126** [comment]
I have narrowed this down to caused by a Gutenberg update - more soon!

**Comment by laras126** [comment]
Ahh okay - this is a problem:
```
*[class*='none'] {
 --duotone-base: initial;
 --duotone-foreground: initial;
 --duotone-bg-blend: initial;
 --duotone-fg-blend: initial;
 --duotone-opacity: initial;
 --duotone-spacing: initial;
 --duotone-grayscale: initial;
 --duotone-contrast: initial
}
```

Something in a recent Guten-update added a class that is matching that pattern, so we need to be more specific with that expression so any class containing the text "none" doens't apply this.
