### ISSUE TITLE
Need more consistant styling of radio buttons, checkboxes, and dropdowns in forms

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#207]
We added the Formidable Forms plugin and have been using it. The customizations we made for the GIVE-WP forms interact in weird ways that make the radio buttons disappear.

Here's a form we added:
https://c4aa.org/artistic-activism-master-class

The dropdowns, radio buttons, and checkboxes are unstyled.

The [donate form](https://c4aa.org) radio buttons are great but the checkbox and dropdown are unstyled too:

![Screen Shot 2021-02-21 at 1 54 18 PM](https://user-images.githubusercontent.com/67271/108635433-61614300-744d-11eb-878e-b56d9df6c638.png)

I added this code into the wp-admin to make the formidable stuff work in the meantime:

```
.frm_radio label input, .frm_checkbox label input {
	height: 1rem;
	width: 1rem;
	margin-right: 0.5rem;
	opacity: 100%;
}
```

And this to style it a bit:

```
.frm_description {
	font-size: 15px;
	font-style: italic;
}

.frm_error {
	color: hsla(60, 9%, 98%, 0.9);
	background: hsla(356, 80%, 45%, 0.9);
	font-weight: bold;
  padding: .3em;
}
```

Here's the GIVE/Donate form code we have:

https://github.com/thec4aa/c4aa-org/blob/9828959a49becd0f7f679a06c328f2a530d0d358/src/css/_04-content.scss#L64-L108

And radio button specific stuff:

https://github.com/thec4aa/c4aa-org/blob/9828959a49becd0f7f679a06c328f2a530d0d358/src/css/_03-generic.scss#L391-L418

Here's somethings we've already added for Formidable Forms:

https://github.com/thec4aa/c4aa-org/blob/9828959a49becd0f7f679a06c328f2a530d0d358/src/css/_04-content.scss#L326-L340

**Comment by slambert** [comment]
Note: incorporated some of the above changes this into a hotfix branch cuz we were having problems with our application form.

Basically:
1. added another selector to the radio button changes we had so they wouldn't effect the other form
2. incorporated some styling to the formidable forms we're using. 

You can see all the commits in this branch:

https://github.com/thec4aa/c4aa-org/tree/sl-hotfix-202102

**Comment by slambert** [comment]
I created a test/sample form here: https://c4aa.org/?page_id=19118 (it's a draft page)

Things to note:

[] Some of the fields that would extend across the page are shorter (like Address 1, Address 2)
[] radio buttons aren't styled
[] checkboxes aren't styled
[] dropdowns aren't styled
[] LOW PRIORITY: Rich text WYSIWYG editor is partially styled 
[] toggles are unstyled
[] scale should go horizontally accross the screen
[] slider needs some design

**Comment by andrewheins** [comment]
Due to the number of collisions between this and GIVE and the fact that I can't figure out where the Formidable Forms actually are on pages, I'll need a bit of help here @slambert

**Comment by slambert** [comment]
I made a test form and put a bunch of stuff in it.

https://c4aa.org/separator-test
password is separator

This was, also something I made to test the separators

**Comment by andrewheins** [comment]
@tinuola  Would you be interested in looking at this? 

You can also look at the forms that show up on the Fellowship application pages: https://c4aa.org/2023/10/open-call-unstoppable-voters-fellowship#application

**Comment by slambert** [comment]
Talked to designer today and should have answers before the end of the month.

**Comment by slambert** [comment]
@andrewheins Ok here's the specs!

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/f84682bf-1cc1-4cd8-b65c-2ee8e116dbc3)

**Comment by slambert** [comment]
Most of this is done in #207 and on the staging site.

What's left is radio buttons but it's not critical. Dropdowns we can skip.

...I think I'll make that a separate ticket.
