### ISSUE TITLE
Editor styles are incomplete

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#216]
**Describe the bug**
Editor View doesn't really match published view.

**Expected behavior**
The editor view for a page should roughly match what the end product will look like. 

**Definition of Done**
- When a page is being edited in the Gutenberg editor, what you see should more closely resemble what you'll get.

**Comment by slambert** [comment]
Generally what you see in the editor is not representative of what you'll see on the page and it would be great if they matched more closely.

**Comment by andrewheins** [comment]
This feels like something we  could address with the build process. If we had it build both the front-end CSS and a separate, prefixed admin.css, we could pull the same styles into the editor in such a way that it's much closer to WYSIWYG

**Comment by andrewheins** [comment]
Updated to request.

**Comment by slambert** [comment]
Well, I found out the editor styles weren't linked correctly:

https://github.com/thec4aa/c4aa-org/commit/c11f44ca96aeb868a7c9a7e7e1ef49ad180ef587

I'm not really working on this, just started exploring. Please, someone else, take it.

**Comment by slambert** [comment]
Needs testing, but I think this may be done.
