### ISSUE TITLE
Nice up the Footer

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#22]
- [x] Remove .imprint
- [x] Add CC license
- [x] Add Privacy Policy page and link
- [x] Check out style of footer with footer menu.
- [x] make sure footer text is accessible

branch is sl-style-footer

We can do better than " Center for Artistic Activism, Proudly powered by WordPress. "

**Comment by slambert** [comment]
@laras126 can you add an over-riding footer template to the child theme so I can mess with this.

Also, thinking about using Font Awesome icons, for adding the Creative Commons license but... are those useful anywhere else that I could justify installing the plugin?

**Comment by laras126** [comment]
Don't use the plugin - we can add the icon with an SVG!

**Comment by slambert** [comment]
Add privacy policy. 

Stuff to remember: https://www.wpbeginner.com/beginners-guide/how-to-add-a-privacy-policy-in-wordpress/

**Comment by slambert** [comment]
@laras126 I added the Creative Commons svg file and footer.php file to this and gave it a try, but I'm not sure the best way to go about it.
