### ISSUE TITLE
Feature: check color of group that element is within and change colors accordingly.

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#220]
**Is your feature request related to a problem? Please describe.**
When text is nested in a colored group, it would be nice if the text and link color changed automatically.

**Describe the solution you'd like**
When a dark background color is applied to any element, child elements should automatically receive light color styling.

**Additional context**

**SEE COMMENT BELOW**

It works kinda like this:

- Group - background color red
- Paragraph - no color settings  
Links are red by default.

- Paragraph - background color red
Links are not red by default

![Screen Shot 2021-08-26 at 1 10 36 PM](https://user-images.githubusercontent.com/67271/131009533-118367ef-a892-477b-a6a4-d8d70e8cb859.png)

**Guidance**
There are a limited numbers of colors in the theme, and only three of them (red, black, blue) should force white text.
Whenever a background is applied to a group, it gets a few classes:

`wp-block-group alignwide has-caa-red-background-color has-background`

It should be possible to style child text and links inside a group that has a class of has-caa-red, has-caa-blue or has-caa-black

**Definition of Done**
- When a dark background color is applied to a group, the contents will automatically get modified so that links and text are light.
- PR submitted referencing this issue.

**Comment by slambert** [comment]
With the new color options we created in Gutenberg, this may no longer be as necessary.

**Comment by andrewheins** [comment]
Upgrading to request

**Comment by slambert** [comment]
> With the new color options we created in Gutenberg, this may no longer be _as_ necessary because our staff can change it. But with links, it will be needed.

This might be less necessary because you can color text and links within the block editor now. Let's get further with #299 and #268 and see how easy it will be to solve this on the user side.

**Comment by slambert** [comment]
I don't think this is necessary anymore. Closing for now.
