### ISSUE TITLE
Right aligned images don't right align

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#224]
This would be a handy thing if it worked!

### Block view

<img width="1128" alt="Screen Shot 2021-09-17 at 4 14 07 PM" src="https://user-images.githubusercontent.com/67271/133848444-0f1324c1-0d16-4172-9225-45ecfed3531a.png">

### Page view

<img width="886" alt="Screen Shot 2021-09-17 at 4 14 39 PM" src="https://user-images.githubusercontent.com/67271/133848451-901dbfe3-1653-4d08-b4c8-78bfa4a4e6b0.png">

**Comment by slambert** [comment]
This does work for pullquotes, by the way.

**Comment by slambert** [comment]
Maybe related to #189

**Comment by laras126** [comment]
We can resolve this and #189 by using the WP core duotone configuration through theme.json. A couple of things need to be added to achieve the same functionality as what we have:
1. hover style to remove the filter
2. the `color-burn` blend and 0.69 opacity for Beige and Grey Vintage (this might be accomplished by adding a block style called "vintage" that works with the Black and Beige duotone)

**Comment by slambert** [comment]
>  hover style to remove the filter

this would be cool, but can come later if necessary.

> the color-burn blend and 0.69 opacity for Beige and Grey Vintage (this might be accomplished by adding a block style called "vintage" that works with the Black and Beige duotone)

@laras126 This one is the one we use the least (the number of images it looks good on is smaller than I'd hoped) so we can just drop it and put effort elsewhere.
