### ISSUE TITLE
Editor styles leave no margins

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#228]
![Screen Shot 2021-11-26 at 4 13 51 PM](https://user-images.githubusercontent.com/67271/143654925-309f3cc3-1e47-43e5-b3ac-72448e5420be.png)

**Comment by slambert** [comment]
When you do full width, sometimes the block settings become inaccessible.

In general, I love the editor styles and wish they matched more closely! But this can make it tricky to edit.

**Comment by laras126** [comment]
@slambert Can you share a post where this is happening? Not able to replicate – also I'm not seeing the option for wide alignment at all, which is confusing...

**Comment by slambert** [comment]
> also I'm not seeing the option for wide alignment at all, which is confusing

Oooh, I'm not seeing it either! I wonder if that was part of Gutenberg? Or needs to be enabled in theme.json?

**Comment by slambert** [comment]
Tested - Gutenberg doesn't bring it back, so I'm guessing it's enabled in the theme settings?

**Comment by slambert** [comment]
https://developer.wordpress.org/themes/advanced-topics/theme-json/#a-theme-json-can-be-added-to-any-theme

> Additionally, the alignment mechanism for “full” and “wide” blocks works differently with a theme.json present and should be considered.

Looks like it's here:

https://developer.wordpress.org/themes/advanced-topics/theme-json/#layout

**Comment by slambert** [comment]
It's good enough now

**Comment by slambert** [comment]
## To reproduce:
1. make a group and mark it full width
2. the content kinda disappears
