### ISSUE TITLE
Gutenberg changed pullquotes under header

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#229]
**Describe the bug**
Gutenberg released a change at some point that broke the current implementation of BlockQuotes for new entries.

Blockquotes no longer get assigned the class `is-style-solid-color` when you choose a background color. Our styles are contingent on that class's presence.

**To Reproduce**
1. create a post
2. make a pullquote as the first block, set it to full width.
3. Preview

**Expected behavior**
View https://c4aa.org/about. The block that starts "Through innovative research and providing ..." is a pullquote set to full-width and has padding and a background color. That's the intended default. 

**Screenshots**
<img width="1676" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/9f91ceef-2d08-41ee-9be5-2539d6923188">
_correct_

<img width="1680" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/283203b8-7181-4066-bdcb-83afec7fb375">
_incorrect_

**Guidance**
We should probably move the required padding over to .wp-block-pullquote.alignfull, and add the background color to .has-c-4-aa-red-background-color

**Definition of Done**
- Adding a full-width blockquote to a new page should have the appropriate padding and styling by default
- PR submitted that references this issue

**Comment by andrewheins** [comment]
Updated to full request.

**Comment by tinuola** [comment]
@andrewheins I'll take this.

**Comment by andrewheins** [comment]
@tinuola  Awesome. Make sure I get an estimate. We do have limited budget.

**Comment by tinuola** [comment]
@andrewheins This was an hour.
