### ISSUE TITLE
Standardize when links should be underlined

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#230]
**Describe the bug**
Underlined links are inconsistent across the site

**Expected behavior**
- Links in content text should be underlined.
- Links in Headers should underline on hover.
- Links in Groups (see screenshots section) should not be underlined 

**Screenshots**
<img width="396" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/be55b31c-31ec-42ee-81d3-be4576459f91">
_link in Group_

**Definition of Done**
- Link underlines behave consistently across the site
- PR submitted that references this issue

**Comment by slambert** [comment]
<img width="1302" alt="Screen Shot 2022-02-22 at 11 13 18 PM" src="https://user-images.githubusercontent.com/67271/155260748-9c2dd6ff-42ee-48c8-8f8f-56181cde61b1.png">

Here's a screenshot - surprisingly inconsistent!

**Comment by slambert** [comment]
Also it would be nice if any linked header underlined on hover, instead of all the time.

**Comment by laras126** [comment]
Any link inside a heading, underline on hover

**Comment by andrewheins** [comment]
Upgraded to request.

**Comment by slambert** [comment]
We're using gutenberg groups more, and differently, than before so let's strink the part about "groups" and focus on underlines on headers

**Comment by andrewheins** [comment]
@slambert Fix merged to staging. Looks good to me. Confirm it's what you expect, and we can merge to prod
