### ISSUE TITLE
Images on about page not rendering on chrome

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#235]
**Describe the bug**

**To Reproduce**
Currently, we're unable to reproduce. If you find a way to replicate this, please add your step as a comment below.

The issue generally occurred when a duotone filter was applied to an image in a column.
<img width="675" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/c1e31ebc-248b-4dfb-9618-6d7106bdd4a7">

**Expected behavior**
Putting the duotone filter on an image shouldn't cause any image display issues, while filtering the image to be greyscale.

**Screenshots**
<img width="1163" alt="Screen Shot 2022-02-28 at 3 26 41 PM" src="https://user-images.githubusercontent.com/67271/156054004-8cdbe919-20f9-4d75-b01d-04f76f8d2fbf.png">
_Brave Browser_

<img width="1003" alt="Screen Shot 2022-02-28 at 3 27 12 PM" src="https://user-images.githubusercontent.com/67271/156054133-81dfe372-f19e-4690-b742-7339a6e8f0b9.png">
_Firefox_

**Comment by slambert** [comment]
You won't see this now because we re-did it. 

I figured it out though - it's images that have our old duo-tone class within a table. If I remember correctly.

**Comment by laras126** [comment]
On this page towards the bottom - https://c4aa.org/about

**Comment by laras126** [comment]
@slambert Is this issue resolved then (dev-wise), just waiting for changes to the content to remove the old duotone class?

**Comment by slambert** [comment]
What I hoped was we could make some change that would get those images to appear. I can catch everything on that page, but I'm not sure where that combination of columns and duotone class shows up elsewhere.

**Comment by andrewheins** [comment]
Updated to full request, though I would consider this lower priority as it's currently not reproducible.

**Comment by slambert** [comment]
Actually - because now duotone is handled by Gutenberg (we were so ahead of the curve on that!) would it be smart to remove the duotone stuff from our code? 🤔 It may get used on featured images in posts & pages and if so, it probably needs to stay.

**Comment by slambert** [comment]
This seems solved - we haven't seen a problem with duotone in columns disappearing. So, closing for now.
