### ISSUE TITLE
Add this CSS for the Matomo Heatmap

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#237]
**Describe the bug**
When viewing a heatmap in Matomo, the hero section of the site often expands significantly, making it hard to determine where the heatmap hits actually land. 

**To Reproduce**
1. Login to Matomo
2. Go to "Heatmaps"
3. Open an active heatmap, like "Unstoppable Voters Landing Page"

**Expected behavior**
Page renders in Matomo similar to how you see it normally in browser

**Screenshots**
<img width="1302" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/1b048cae-0a61-4c4c-a647-48fa421f2f6b">
_in Matomo_

<img width="1673" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/37ee7e32-53c6-482d-99cd-0a69f6ddc06e">
_in browser_

**Additional context**
https://matomo.org/faq/heatmap-session-recording/faq_24421/

> If you use “Parallax Scrolling”, or when a part of your page is set to 100% of the browser height, the heatmap might not be shown correctly. Typically, the header would be shown stretched over the whole heatmap and other parts of the web page would not be visible. To solve this problem, set a max height to this element using CSS or JavaScript. For example:
> 
> `.welcome { max-height: 1000px; }`
> 
> If you want to set this style only for Heatmaps, you can prefix your selector with “html.piwikHeatmap”:
> 
> `html.piwikHeatmap .welcome { max-height: 1000px; }`
> 
> The chosen 1000px is only an example, you can set it to any height. Learn more about custom stylesheets.

**Definition of Done**
- styles are updated such a that Matomo issue is resolved
- PR is submitted referencing this issue

**Comment by andrewheins** [comment]
Hi @slambert! Do we still use Matomo? If so, could you email me the account credentials so I can verify the issue and create a thorough request issue?

**Comment by slambert** [comment]
Ah, here's the answer! I will send you info.

**Comment by slambert** [comment]
@andrewheins I was just thinking, if you want to archive the old data feel free. It may not be as useful? Your call.

**Comment by andrewheins** [comment]
This has been an absolute nightmare to fix. @slambert Another heatmap tool we've had positive experiences with is Microsoft Clarity. It's free, and has been a solid pickup. Would you be open to me trying that instead?

**Comment by slambert** [comment]
This could be a solution?

https://matomo.org/faq/heatmap-session-recording/faq_24426/

Otherwise, please move forward.

**Comment by andrewheins** [comment]
No luck. Closing this issue, as we now have MS Clarity.
