### ISSUE TITLE
H3 headers split words

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#239]
**Describe the bug**
If words are too long in H3 headers, they get split between two lines instead of the text getting smaller. OR alternatively, just break layout overall. 

**To Reproduce**
@slambert I'm having trouble reproducing this one. Do you mind providing a link or something similar?

**Expected behavior**
h3 headers should naturally break with a hyphen when words get wider than the content box. Hypenation when necessary, but only when necessary.

**Screenshots**
<img width="482" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/1f0c192b-0bec-469a-b7a5-ec20c8a410af">
_Current test_

**Definition of Done**
- CSS rules have been put in place across the board to implement logical hyphenation.
- PR submitted referencing this issue

**Comment by andrewheins** [comment]
@tinuola I'd love to get this quickly addressed as well.

**Comment by slambert** [comment]
> @slambert I'm having trouble reproducing this one. Do you mind providing a link or something similar?

You're right... I can't find where that problem was showing up now. 🤔
