### ISSUE TITLE
Style dropdowns for menu

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#240]
**Is your feature request related to a problem? Please describe.**
The current site navigation starts to wrap when too many items are added to the site. This doesn't break anything, but it doesn't look or feel great.  We're like to be able to group and expand the navigation to provide better, faster access to different parts of the site. 

**Describe the solution you'd like**
The first step to resolve this seems to be to style the dropdowns in a way that makes them usable and matches the design

**Reference**
<img width="549" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/6369b5aa-ffa4-417a-94b3-022b38515139">
_Current State_

**Definition of Done**
- Dropdowns are designed such that if Menu items are added as children of a parent, they display properly as well-designed dropdowns.
- PR submitted referencing this issue.

**Comment by zenbug** [comment]
Okay I will have an estimate to you early next week.

**Comment by zenbug** [comment]
So sorry for the delay on this! My machine was not functioning properly so I couldn't properly look at this site's setup.

I think including coding and back-and-forth approvals, this would take about 3 hours.

**Comment by andrewheins** [comment]
Please proceed!

**Comment by zenbug** [comment]
Can you all have a look at this video and let me know if this solution works for you?:
https://www.loom.com/share/8e2b5e8a6fbc46469fa7ffd3550f9230?sid=a2ad2f94-2237-4cfd-a0bb-9d52f61f2c47

**Comment by andrewheins** [comment]
@slambert @zenbug It works, but I'm just not sure it fits with the design overall. It feels cramped, the padding is a bit inconsistent. I don't hate the arrow as a single, but I think if you had multiple (5) sub-items, it would be too busy. 

I think a solid brand color on the background of the nav with a bit more padding might make it feel more part of the design.  Open to @slambert's thoughts as well.

**Comment by zenbug** [comment]
Something along these lines?:
![mockup-1](https://github.com/thec4aa/c4aa-org/assets/806080/2149c0f6-b6a1-4fdd-9519-a63fea6df0f0)

**Comment by slambert** [comment]
The black, now that I see it, might be a little heavy. But we've got a designer we're working with and I'm meeting with him tomorrow. I can run this by him and try to get you some more solid feedback.

**Comment by slambert** [comment]
Ok, I talked with Andy our designer and he came up with this mockup which we'd like to use. It involves another change to the logo in the header and notes about mobile. @andrewheins you can decide if the logo change and addition of social icons should become a separate issue. Sorry we couldn't get this earlier but it wasn't possible. ¯\\_(ツ)_/¯

The screenshots include some other changes Andy is working on with fonts and colors, and we'll get to those soon. 🙂

Let me know if you need more info.

* * *

Please see the initial studies for the website navigation attached.

The basic premise is that each top-level item is contained in a red “rubylith tape” shape (which could stand to be a little more irregular than I've drawn here, with a charcoal gray overlay pane for the drop down. The logo lockup is now at upper left, and social media icons (also over rubylith). The charcoal overlay could have slightly wider left margins on the submenu than I am showing here.

![Top_Nav_Study-01](https://github.com/thec4aa/c4aa-org/assets/67271/6fd56547-78dc-4f92-a7b4-e3f8c0ccbcc7)

![Top_Nav_Study-01A](https://github.com/thec4aa/c4aa-org/assets/67271/aa117d57-cbca-4a97-af38-f29803981ec5)

On mobile, the nav is triggered by a burger (also rubylith - an svg?). This opens a pane with the main nav items. The secondary items could open when the main item is tapped (as shown), but that might be overkill on mobile. (Comps are 2x)

![C4AA_Mobile-01](https://github.com/thec4aa/c4aa-org/assets/67271/41814e63-ed53-4802-a667-e56a43da387b)

![C4AA_Mobile-01A](https://github.com/thec4aa/c4aa-org/assets/67271/12fede25-fa79-4c7e-9ba5-386c321e0e99)

**Comment by zenbug** [comment]
Hi folks.

So I'll need to revise my estimate of 3 hours for this. It's more like 7 hours for this kind of customization. There is currently no collapsed mobile menu at all in the theme, so this will involve more than just adding CSS.

Please advise?

**Comment by andrewheins** [comment]
@slambert How do you feel about that overall? It would unlock a lot of options for reworking the AI of the site, but I definitely want your approval before approving work of this size.

**Comment by slambert** [comment]
> It would unlock a lot of options for reworking the AI of the site

What does AI stand for in this context? 😬

I think it's smart. The only question I have is would it be smarter, long term, to move to one of the more current base theme that has a mobile menu already?

**Comment by andrewheins** [comment]
@slambert A more current base theme would likely be an enormous (40+ hour) project if we were to try to implement a similar style to what you already have, so this definitely represents a smaller lift.

Also, I wrote "AI" instead of "IA" and confused everyone. This is why acronyms are bad. "Information Architecture" was what I was _trying_ to communicate.

**Comment by slambert** [comment]
Got it - let's do the smaller lift! 👍

**Comment by andrewheins** [comment]
@zenbug Let's get moving on this ASAP. You have approval

**Comment by zenbug** [comment]
Working on this today.

**Comment by zenbug** [comment]
The site logo in these mockups is not the one currently on the site. Can I get those logos? Both the colour one and the white one?

**Comment by andrewheins** [comment]
@slambert  Do you have those logos? I don't believe that I do.

**Comment by slambert** [comment]
Sent over a request to Andy...

**Comment by slambert** [comment]
Here's the logo files:
[C4AA_Logo_AI.zip](https://github.com/thec4aa/c4aa-org/files/13302078/C4AA_Logo_AI.zip)

**Comment by zenbug** [comment]
Thanks @slambert! Working on this today.

**Comment by zenbug** [comment]
Pull request made for this: https://github.com/thec4aa/c4aa-org/pull/264

**Comment by andrewheins** [comment]
@slambert Ok, the navigation is now up on https://backtobasics.c4aa.org/. If you wanted to review and approve for production deployment.

**Comment by zenbug** [comment]
@andrewheins Looks like for the logo on mobile, I left absolute paths rather than relative:

https://c4aa.local/wp-content/themes/c4aa-org/img/logo-c4aa-red.png
https://c4aa.local/wp-content/themes/c4aa-org/img/logo-c4aa-white.png

Did you want me to fix that or you?

**Comment by andrewheins** [comment]
If you can handle quickly, that would be great.

**Comment by zenbug** [comment]
I don't seem to have access to the `develop` branch on my cloned repo, even though it does say the fork-sync is current.

**Comment by andrewheins** [comment]
@zenbug It's a bit different than you might expect. Here's a loom: https://www.loom.com/share/f00e2916287b4d89bbe5869c989eed9f?sid=cb6bb034-11b2-4c2f-a0e9-05b4d2f50841

Hopefully there's noise reduction, because I'm in a Starbucks right now.

**Comment by zenbug** [comment]
So I tried this, but I got an error that started with this:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is...
```

I followed the instructions here:
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

But now I get this:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is it possible that I need access this repo that I don't currently have?

**Comment by slambert** [comment]
Hey all, had a chance to look at the new navigation - overall looks great. One thing – the red logo on the right on full width doesn't need to be there. It's redundant with the full logo on the left.

Besides that I think we're good.

**Comment by zenbug** [comment]
I just submitted a pull request. I addressed the logo issue, but I couldn't find out why the flash is happening. Personally I'm not too worried about it because as Steve said, there's no hover on smartphones where virtually all visitors will be using that menu.
