### ISSUE TITLE
Magic Hand missing from footer

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#241]
**Describe the bug**
The Magic Hand, which should be present, centered, in the footer, is missing.

**To Reproduce**
1. Look at the footer on any page

**Expected behavior**
Magic Hand Icon should be present and centered.

**Screenshots**
_Current_
![Screenshot 2022-11-20 at 2 44 30 PM](https://user-images.githubusercontent.com/67271/202922671-2b952e17-afc6-47db-993d-3cdec180c3b6.jpg)

_Intended_
<img width="582" alt="image" src="https://github.com/thec4aa/c4aa-org/assets/365853/059e409a-0534-4dbe-a124-ebb33729e02e">

**Technical Guidance**
Update the icon itself to have styles similar to:
element.style {
    object-fit: contain;
    width: 100%;
    height: 100%;
}

**Definition of Done**
- Footer styles are updated to properly show the Magic Hand icon.
- PR submitted referencing this issue.

**Comment by andrewheins** [comment]
Upgraded to request.

**Comment by tinuola** [comment]
@andrewheins  I'll pick this up. Tx.

**Comment by andrewheins** [comment]
Hi @tinuola, 

I merged this but it didn't have the desired effect. Because the SVG itself has no intrinsic size, it just smushes down to 0x0. 

There's a suggested fix in the issue outline. Can you just implement that in _03-generic.scss:457?

**Comment by tinuola** [comment]
@andrewheins I can see the icon on the live site.
