### ISSUE TITLE
Add EIN number to footer

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#242]
**Describe the solution you'd like**
Our fundraising person asked us to add our EIN number to the footer. That part of the site is embedded in the code.
EIN: 45-3557000

**Technical Guidance**
https://github.com/thec4aa/c4aa-org/blob/9828959a49becd0f7f679a06c328f2a530d0d358/footer.php#L29-L32

It makes sense that we'd add it on a new line below the city and phone number.

**Definition of Done**
- EIN listed above is referenced in the footer
- Pull Request is made referencing this issue

**Comment by andrewheins** [comment]
Updated to formal request.

**Comment by andrewheins** [comment]
@tinuola  Super fast item I'd love it if you could address.
