### ISSUE TITLE
Restyle buttons

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#246]
Staff has said the buttons look too different from the rest of the design. They should still be identifiable as _buttons_ and not confused with a header. But some don't use them because they think they seem out of place and want something more consistent with the rest of the design. This is totally subjective, but hopefully inspires something... 

Ideas:
- update the colors.
- Keep the animation, but make them simpler.

**Comment by andrewheins** [comment]
Closing, with new formal request at #250
