### ISSUE TITLE
Whitespace above header images

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#257]
**Describe the bug**
Header images now don't fill the space.

(_I know this might be a necessary side effect_ of #254 and I'd prioritize that, but just wanted to make sure can't get the best of both worlds? 🙂)

**To Reproduce**
1. Go to https://c4aa.org/what-we-do
2. Resize the browser window, make it very tall 
4. Whitespace appears above and below the header image.

**Expected behavior**
Maybe not expected, but hoped for behavior is that we could have the image fill that window.

**Screenshots**
![Screenshot 2023-09-21 at 9 44 01 AM](https://github.com/thec4aa/c4aa-org/assets/67271/d9a2952c-54ab-4e23-8636-ecc8dcf649f0)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Firefox! 
 - Version 117.0.1 (64-bit)

**Comment by andrewheins** [comment]
@slambert  Sorry, that's my Matomo fix. I didn't have a monitor big enough to see the issue you saw. Pushing a fix now.

**Comment by andrewheins** [comment]
Fix deployed.
