### ISSUE TITLE
Newsletter form needs styling

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#26]
See also: https://github.com/thec4aa/c4aa-org/issues/10

Mailchimp form has some inline styling we can probably take out.

Check it out at: /newsletter

**Comment by slambert** [comment]
I took out the inline styling.

@zoracreates I think this is ready for ya.

**Comment by zoracreates** [comment]
I would recommend adding a label of "Email address" to the newsletter input. It's[ not accessible to use the placeholder attribute as a replacement](https://www.smashingmagazine.com/2018/06/placeholder-attribute/).

```
<label>Email Address

<input id="mce-EMAIL" class="email" name="EMAIL" required="" type="email" value="" placeholder="email address">

</label>
```
