### ISSUE TITLE
Update colors and fonts to 2024 design

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#268]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Update fonts

Replace Raleway with Zilla Slab
Replace Roboto with WorkSans

https://fonts.google.com/specimen/Work+Sans
https://fonts.google.com/specimen/Zilla+Slab

Update colors

Adjust colors on the site to the colors of our new design.

Update the color palette offered in gutenberg.

**Describe alternatives you've considered**
n/a

**Additional context**

## Primary Palette:

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/1de817ea-0736-4034-b489-a748995dd4ad)

## Typography
![Image](https://github.com/thec4aa/c4aa-org/assets/67271/9357694e-77c8-4a51-bfa1-e705ce3e7e82)

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/2f7f1512-c943-46f3-9621-8c21e9d29263)

# Secondary Palette & Combinations

![Screenshot 2024-04-09 at 2 15 47 PM](https://github.com/thec4aa/c4aa-org/assets/67271/791ee552-6470-409b-a585-8be2082c4e5a)
![Screenshot 2024-04-09 at 2 20 33 PM](https://github.com/thec4aa/c4aa-org/assets/67271/f7f019ed-4c25-49cc-b833-e144d4ff0c50)

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/7afc5c95-5b4c-4573-af75-daef13fbfae3)

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/608d4b1d-d755-4ea2-9560-8c16fd17dde3)

**Comment by andrewheins** [comment]
@ashokmladumor Can we get an estimate on how long implementing these new styles would take. There's a significant amount of work here, but this is our highest priority of everything on C4AA right now. 

For the most part, we feel like these are just going to be 1:1 replacements of existing CSS variables and font, with a few additions.

**Comment by ashokmladumor** [comment]
@andrewheins After reviewing the site, I found that designs on various pages are different. Adding a new font might slightly disrupt the current design, so we'll need to adjust. This includes updating CSS variables and fonts to match the new style and ensuring everything looks good. Overall, implementing these changes could take approximately 8 hours.

**Comment by andrewheins** [comment]
@ashokmladumor  Please proceed. Let know if you get close to the estimate.

**Comment by slambert** [comment]
@ashokmladumor [I replaced the png in the logo with a transparent one](https://github.com/thec4aa/c4aa-org/pull/294). It may help as we shift the colors on the site.

**Comment by ashokmladumor** [comment]
@slambert  Sure, can you help me understand where I can use primary and secondary color palettes? I'm having trouble figuring out which section's background color needs to be changed.

**Comment by slambert** [comment]
@ashokmladumor If you’re not sure, just use the primary with the grey. I can go in and adjust as needed.

If you're adding the palettes in the interface, you can add all the colors.

**Comment by ashokmladumor** [comment]
@slambert @andrewheins Added all primary colors to palettes and changed all fonts. #304

**Comment by slambert** [comment]
Thanks @ashokmladumor - Today I'm going to look at our two branches and put them together, then move it into develop.

**Comment by slambert** [comment]
I think we can call this done.
