### ISSUE TITLE
Size of pullquotes under headers is wrong/inconsistent

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#269]
For reference, what's on the homepage is correct.

**Describe the bug**
 Pullquote text is automatically bold and too large.

**To Reproduce**
Go here: http://c4aa.org <-- the pullquote text is the right size.
Go here: http://c4aa.org/about <-- the pullquotes are bolded and larger
This is captured in screenshots below.

Looks especially bad in mobile.

**Expected behavior**
By default, pullquote text should be smaller and not bold. I suspect some gutenberg thing changed this.

Also, unsure about this, but long words should not be hyphenated or wrap mid word in these pullquotes and I can see that happening in mobile.

**Screenshots**

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/07197626-2f4b-4106-b60b-88ccdbe1938f)
![Image](https://github.com/thec4aa/c4aa-org/assets/67271/53ffa830-56fa-4a5a-ba0a-bee30be76d88)
![Image](https://github.com/thec4aa/c4aa-org/assets/67271/6beae56e-8d9d-4efe-9710-ea032b3b7774)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 121.0.1

**Additional context**
Let's test that changes fix (as many of) the existing places this shows up. If there's a few strays, that's ok.

**Comment by andrewheins** [comment]
@ashokmladumor Let's get you moving on this one too.

**Comment by slambert** [comment]
This is an example, from the home page, of what the text should look like.

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/1bcccef6-b199-4fb5-99a8-7cbac1f40ee0)
