### ISSUE TITLE
Make link underlines smaller and adjust line height

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#273]
**Is your feature request related to a problem? Please describe.**
underlines for links are too heavy and come too close to the tops of the letters in the line below when the line wrap.

For an example look at the recent news here: https://c4aa.org/links

**Describe the solution you'd like**
1. 1px underline
2. Even out line height.

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Additional context**

![Image](https://github.com/thec4aa/c4aa-org/assets/67271/5c14e95d-22c5-43d8-ace4-49510161d520)

**Comment by andrewheins** [comment]
@ashokmladumor Can you take this on please? The image that @slambert attached looks to be their desired state. The current state looks much more crushed, so let's try to match the image.

**Comment by slambert** [comment]
Should be closed by [this commit](https://github.com/thec4aa/c4aa-org/commit/d8738704c7cdd1e53c3d0ef96663638ce9463cdd)
