### ISSUE TITLE
Third Party iframe form adds extra space

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#274]
**Describe the bug**
The iframe includes a lot of blank space under the form.

**To Reproduce**
1. Go to '[donate page](https://c4aa.org/donate)'
2. Scroll down to the donate form
3. See extra space

**Expected behavior**
A reasonable amount of space under the form.

**Screenshots**

![Screenshot 2024-01-31 at 9 41 10 AM](https://github.com/thec4aa/c4aa-org/assets/67271/2361dd13-3f97-4e88-b774-1648a211e8f5)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Firefox
 - Version 121.0.1

**Comment by andrewheins** [comment]
@slambert I've reviewed this and I think this is actually something that the embed system does intentionally because the form _can_ be longer, so they provide extra room. I hope this isn't too much of a problem.

**Comment by slambert** [comment]
[This ](https://github.com/thec4aa/c4aa-org/commit/98b43286c366c75009dce68766e2a79bae450b96) change should fix it. If we ever need to change it back, we take out that bit of css.
