### ISSUE TITLE
Include RSS feed in the header

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#275]
**Is your feature request related to a problem? Please describe.**
I was just playing with an RSS thing and noticed we have no link to an rss feed in our header. They exist, but there's no link.

**Describe the solution you'd like**
Include 
`<?php bloginfo( 'atom_url‘ ); ?>`
in the header

**Describe alternatives you've considered**
There's other feed formats [but atom seems to be the best](https://stackoverflow.com/questions/3489578/which-is-most-used-rss-or-atom-and-which-one-is-better-to-build-from)

**Additional context**

**Comment by andrewheins** [comment]
@ashokmladumor Go forth!

**Comment by ashokmladumor** [comment]
Hey @andrewheins, I fixed the issue and created a pull request. Should I go ahead and merge it into the master branch, or do we need someone to review it first?
