### ISSUE TITLE
Create a "People" Custom Post Type

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#284]
**Is your feature request related to a problem? Please describe.**
We're moving all "People" from sub-pages under the About Page, to posts with the category "People"

**Describe the solution you'd like**
1. Remove the header image, so it looks like it would if no Featured Image was assigned.
2. Remove metadata below header image (Author, Date, Edit)
3. Change the metadata at the bottom to remove the author and date, and include category and tags.

**Describe alternatives you've considered**
template part? if_category ? add_filter in features.php? I thought about a few ways you could make this happen but I'm not smart enough in that way.

**Additional context**
It should look like an individual page does. For example: https://c4aa.local/about/brett-davidson

But it does look like this:

![Screenshot 2024-03-29 at 4 57 57 PM](https://github.com/thec4aa/c4aa-org/assets/67271/fa211877-5009-4992-a065-6661d5469a9e)

**Comment by andrewheins** [comment]
@ashokmladumor the way that I would advise that we approach this is to create a custom post type for Person. 

- Create the custom post type for Person
- Copy the data from all of the existing Person pages over to the new Custom Post Type (should be build in Gutenberg page builder)
- Check to see which template is being served for people, and probably copy the one we want (page.php) and create a single-person.php file to render the correct output in the child theme. 
- Create redirects for each person page (there are < 30) to the new URL, which will live at /people/[slug]

**Comment by slambert** [comment]
Created this with Advanced Custom Fields and will be styling it all soon.

**Comment by slambert** [comment]
I did this. Couldn't figure out how to override the twentynineteen_can_show_post_thumbnail function so I just used ACF for that image instead.
I think this may be set.
