### ISSUE TITLE
style .site-branding-container (site header)

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#3]
```
.featured-image .site-branding-container {

    background: #968c83;
```

See how it feels. If we need to, we can darken it down.

**Comment by slambert** [comment]
Or perhaps - white and opaque - like the header of the current site.  Sorry, I may need to see both to know 😬

**Comment by slambert** [comment]
Hi all,

I made a mockup in Photoshop that kinda builds off our letterhead.

I know there's some decisions to make when the header scales down for smaller devices. I was thinking for that - take away the words "The Center for Artistic Activism" and the red dash, and just leave the menu and the small logo on the right. Good right?

I also realize this has multiple steps to accomplish in the css like:
- recentering the image below
- moving the logo from the left to the right
- adding the name of the org
- adding the slash (this and the above could be done with an image, if that makes $ense, but css would be cool)
- making adjustments for mobile and smaller browser windows.

It's significant, but look at this:

![mockup of header](https://user-images.githubusercontent.com/67271/63654539-9e118880-c749-11e9-9cea-3d4264359479.png)

Whattaya think @zoracreates @laras126?

**Comment by slambert** [comment]
This shouldn't hold the merge for #117, I just have a few requests to get it dialed in. 

#### 0. The red square C4AA logo on the right is still coming

#### 1. more and even spacing around red slash
<img width="1047" alt="Screen Shot 2019-09-19 at 8 57 09 PM" src="https://user-images.githubusercontent.com/67271/65291312-c3af6900-db20-11e9-8705-9f963510d8b7.png">
Let's try the same size spacing between each word of the menu on either side of the red slash

#### 2. put menu text at vertical middle of svg logo
If you look at the below image, the menu text shows up slightly lower than the vertical mid point of the logo. It should be in the middle, or maybe slightly above. (Sometimes there's an optical illusion where the true vertical middle _looks_ too low.)
<img width="1042" alt="Screen Shot 2019-09-19 at 9 06 06 PM" src="https://user-images.githubusercontent.com/67271/65291437-5fd97000-db21-11e9-841b-133a241ea39b.png">

#### 3. put the logo and menu in the vertical middle of the header
There's less space above the logo than below. Let's put it in the middle.
<img width="875" alt="Screen Shot 2019-09-19 at 9 11 58 PM" src="https://user-images.githubusercontent.com/67271/65291616-34a35080-db22-11e9-9602-61f041b6a75d.png">

#### 4. Have the left margin disappear earlier with smaller screens
Here, the menu tucks under the logo while there's still a big margin on the left and right side of .site-branding. Let's lose that margin earlier and keep the bigger menu.
<img width="1073" alt="Screen Shot 2019-09-19 at 9 16 54 PM" src="https://user-images.githubusercontent.com/67271/65291774-d5920b80-db22-11e9-9177-3b078939aabe.png">
 
#### 5. General mobile/small screen check

There's some jumps and changes as the menu gets smaller. Some of this will change with the above, especially with the addition of the square red C4AA on the right so I wont go into too much detail as it's bound to change.

There's a point when the screen is smallest that it's just a couple menu items under the logo. I think it would work better to just have the logo and a "hamburger" icon (or the ellipses in our case) on the right side.
<img width="330" alt="Screen Shot 2019-09-19 at 9 09 42 PM" src="https://user-images.githubusercontent.com/67271/65291876-2570d280-db23-11e9-8b58-66cc5429f6a3.png">

**Comment by zoracreates** [comment]
> 0. The red square C4AA logo on the right is still coming

Since CSS is not working out, just now made a commit where the slash is part of the logo image, so this should resolve the issue

> 1. more and even spacing around red slash
> 2. put menu text and red slash at vertical middle of svg logo
> 3. put the logo and menu in the vertical middle of the header

The commit above also works on these.

> 4. Have the left margin disappear earlier with smaller screens

My only concern with this is that the margin allows the container to line up with the body text of the page. This is not noticeable with the featured-image, but it is when there is no featured-image 

>5. General mobile/small screen check

I tried to put everything in a "hamburger" or just the ellipses, but this is tricky. I'm not 100% sure it can be accomplished with just CSS, just because of the way the theme controls what is collapsed and what isn't. I'd have to do some research on this.

**Comment by zoracreates** [comment]
In terms of the "hamburger" menu, while I agree it's not the most aesthetically pleasing solution, I should also note that there may be some practical usability reasons why Wordpress opted for a partly hidden navigation instead. A study by Neilsen Norman, shows users are 1.5 times more likely to use the partly hidden navigation over the fully hidden hamburger. If we use hamburger, I do think it should have some sort of "menu" identifier.

**Comment by zoracreates** [comment]
> 4. Have the left margin disappear earlier with smaller screens

I've added this on #117.

> 5. General mobile/small screen check

I've removed the ellipsis, and will work on a "hamburger" solution.

**Comment by slambert** [comment]
Hi @zoracreates - sorry for the delay.

Noticed that the menu is centered. Can we have it align left against the logo?

![IMG_0647](https://user-images.githubusercontent.com/67271/66263025-1c862f00-e7ba-11e9-9590-a1ba6d5149f8.jpeg)

As the screen gets smaller the red rectangle logo (why was I calling it a red square before?) pops over the left - great - but can we remove the text logo then to save some space. 

![IMG_0648](https://user-images.githubusercontent.com/67271/66263070-fa40e100-e7ba-11e9-9c2f-60f242a5a0da.jpeg)

Let me know if this doesn’t make sense...
