### ISSUE TITLE
Research and decide on caching plugin

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#32]

**Comment by slambert** [comment]
Installed w3 Total Cache: https://wordpress.org/plugins/w3-total-cache/

# 🤷‍♀ 

Any thoughts or objections @laras126? Is there something else you'd recommend?

**Comment by laras126** [comment]
Totally fine! I usually use https://wordpress.org/plugins/comet-cache/ or Super Cache, but unless there's a problem leave that one in.

**Comment by slambert** [comment]
They're a little spammy with the upgrade notices and... now I am remembering, I think it caused some sort of load issues on our server because processing power wasn't as much an issue as memory... or something. Now I need to look into this...

**Comment by slambert** [comment]
Asked about this with our host, waiting to hear back.

**Comment by slambert** [comment]
Note from our host:

> Yes,  caching plugins for wordpress will cache files to disk, not to
> memory. And on our shared servers disk reading and writing is usually the
> most contested resource so caching to disk can actually make performance
> worse or make things worse all around for everyone on the server. So in
> fact just letting wordpress run without a caching plugin is preferable and
> if you really feel like you need a performance boost we can set you up to
> use our caching proxy server on dolores. This is an nginx server that
> proxies to your site on the origin server. Nginx can be configured to
> cache frequently visited pages to disk locally but since it is a separate
> machine dedicated for this purpose it can read from this disk cache
> quickly improving your site's performance and relieves some of the load on
> the origin server where your site resides and php processes run.
> 
> It is somewhat less convenient than an integrated plugin as you will need
> to take some manual steps anytime you want to clear the cache but so far
> this hasn't been too much of an issue for the members who are using it.


Will remove the plugin and make a mental note if we have performance issues down the road.
