### ISSUE TITLE
Change default fonts to match C4AA style guide

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#34]
The fonts that Diane chose for our print materials aren't possible for us for online use. So I found some worthy matches using the Font Squirrel Font Identifier/Matcherator https://www.fontsquirrel.com/matcherator

## Sans Serif
This is a good match, with lots of font weights and italics
https://www.fontsquirrel.com/fonts/metropolis - but may not be developed enough.

We'll use this:
https://www.fontsquirrel.com/fonts/raleway

And these can be runners up
https://www.fontsquirrel.com/fonts/vision
https://www.fontsquirrel.com/fonts/palanquin

For headers we often end up using the heavy version in all caps with a lot of letterspacing. I can help dial this in.

## Serif

This is probably the best match, but there's not enough variety to work for us: ☹️ 
https://www.fontsquirrel.com/fonts/bitter

This however, has endless weights and italics for each one. Should work well:
https://www.fontsquirrel.com/fonts/zilla-slab

A runner up that has a good amount of variety:
https://www.fontsquirrel.com/fonts/aleo

**Comment by slambert** [comment]
The serif fonts are included in Google Fonts, but I'd rather not ping Google and just host the fonts ourselves. Right?

**Comment by slambert** [comment]
Marking as bottleneck because this could impact styling of other blocks and stuff...

**Comment by slambert** [comment]
Hey @laras126:

If we want to cut down on the number of fonts, I can take out some of the weights, specifically for Raleway. But we could do that later once we have some of the design done. Will create an issue.

I looked at https://github.com/typekit/webfontloader but it seems like you will need to incorporate that and get these active on the staging site. 😬

**Comment by laras126** [comment]
@slambert Check out the staging site and let's talk later about which weights to load. I need to explain a bit how it works.

**Comment by slambert** [comment]
I flipped them so the serif is for the headers and the zilla slab is for the rest. But I think I uploaded an uppercase only version of zilla slab on accident...

**Comment by slambert** [comment]
I did, it's fixed now.

**Comment by slambert** [comment]
Ok - switched it to Aleo, which is just a bit easier to read. We'll keep it like that for now.

Let's talk about weights!

**Comment by slambert** [comment]
After some feedback from Rebecca and sleeping on it, I'm think we should use Raleway and Aleo/Zilla for headlines and other accents, and leave the body text, where people will be reading more than a sentence or two, standard as it's set up with Twenty Nineteen. The default is very readable and using our other fonts for little accents here and there will still communicate the design without sacrificing readability.

(I'm like 80% sure of this decision, so if you have other thoughts let me know.)

**Comment by slambert** [comment]
See #58 - I think this is good enough to move forward (and close this).

**Comment by laras126** [comment]
@slambert What's the status on fonts? Are we good to close this and work on #60?

**Comment by slambert** [comment]
I went back in and changed the sans. Here's the PR: #97

And yeah, I think we can work on #60 now.
