### ISSUE TITLE
Need to style separators

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#4]
**Is your feature request related to a problem? Please describe.**
Separators aren't consistent across the site. 

**Describe the solution you'd like**
Separators should be styled such that they look after themselves in any context. 

**Additional context**
https://c4aa.org/separator-test (password: separators)

**Definition of Done**
- Separators, when used, should size themselves relative to the parent container, and should never overflow. 
- PR submitted referencing this issue

**Comment by slambert** [comment]
Probably smart to add `clear: both` to these separators? I mean, since they're _separating_.

**Comment by slambert** [comment]
This could be "dots":

<img width="558" alt="Screen Shot 2019-08-16 at 6 52 03 PM" src="https://user-images.githubusercontent.com/67271/63202278-f7493000-c056-11e9-8057-c0ad0eb40922.png">

**Comment by slambert** [comment]
[lightening bolt.svg.zip](https://github.com/thec4aa/c4aa-org/files/3522838/lightening.bolt.svg.zip)

**Comment by slambert** [comment]
Wide Line:

Just extend the line all the way to the edge of the browser window and a 7em (or rough equivalent) margin on top and bottom.

I accomplished this with the below hack. 

```
.entry-content hr.is-style-wide {
    max-width: 200vw;
    margin: 7em -20em;
}
```

Also, for now, let's make it black.

**Comment by slambert** [comment]
*Default:*

For this I extended the red line outside the margins of the text and put it at a jaunty (random) angle. 

You can probably do better than this:

```
.entry-content hr {
    height: 4px;
    margin-bottom: 3.5rem;
    margin-top: 3.5rem;
    min-width: 100%;
    text-align: center;
    margin-left: -2vw;
    margin-right: -2vw;
    transform: rotate( calc( var( --rotate) * 1deg ) );
}

```

**Comment by slambert** [comment]
@zoracreates this can be lower on your list. I tried to outline what each of the settings would be.

Would love to keep the flexibility of changing colors in the gutenberg interface, so keep that in mind but we'll see what's possible.

**Comment by slambert** [comment]
Can we add a fourth style?

<img width="2264" alt="Screen Shot 2019-09-17 at 1 23 25 PM" src="https://user-images.githubusercontent.com/67271/65064467-8a270400-d94e-11e9-9976-687c5f044adb.png">

**Comment by zoracreates** [comment]
> **Dots**
> 
> <img alt="Screen Shot 2019-08-16 at 6 52 03 PM" width="558" src="https://user-images.githubusercontent.com/67271/63202278-f7493000-c056-11e9-8057-c0ad0eb40922.png">
> 
> I can turn the lightening bolt into an svg.
> 
> Place the lightening bolt in the center of the page.
> 
> I may do this like 3 dots spaced out, but 3 lightening bolts. But let's see how this looks first.

@laras126 Is it possible to do this with CSS only or does this require PHP to add the images? I tried googling it, but couldn't find anything.

**Comment by zoracreates** [comment]
> Can we add a fourth style?
> 
> <img alt="Screen Shot 2019-09-17 at 1 23 25 PM" width="2000" src="https://user-images.githubusercontent.com/67271/65064467-8a270400-d94e-11e9-9976-687c5f044adb.png">

@slambert I have to look into this, but we can probably do this by adding a Gutenberg block. Is there an SVG for this?

**Comment by slambert** [comment]
Here's an svg:
[stripes.svg.zip](https://github.com/thec4aa/c4aa-org/files/3688643/stripes.svg.zip)

**Comment by slambert** [comment]
Also, could you add the svg using `:before` and a background?

**Comment by zoracreates** [comment]
> Also, could you add the svg using :before and a background?

For some reason, when I used background-image in the css file, images were not showing. At least not when I was trying to replace the text-logo with an svg for #90. To be honest, I haven't tried with this.

**Comment by slambert** [comment]
These have gotten weirder with recent updates; low opacity, small, etc.  The above ideas are nice, but some small changes would be helpful.

Wide - should be 100% width
Default - open to ideas, but 50% and centered?

**Comment by laras126** [comment]
Some interim updates 
<img width="1185" alt="Screen Shot 2021-10-01 at 10 33 26 AM" src="https://user-images.githubusercontent.com/445861/135637886-72c04ab4-4a00-4d00-b69c-ff461ed3c86e.png">
–

**Comment by slambert** [comment]
Some weirdness seen on c4aa.org/donate and I've caught it on a few other pages (I might have to re-lay this out but I'll figure out how to replicate before I do)

![Screen Shot 2021-11-10 at 9 36 26 AM](https://user-images.githubusercontent.com/67271/141132966-28f54960-c9d0-4064-a0cd-c5c7c284562e.png)

**Comment by laras126** [comment]
Should be resolved with #231. Content that uses the separator block and has spacer blocks added to compensate for the issue might be extra spaced out and require some updating.

**Comment by slambert** [comment]
Created a separator test here. 

https://c4aa.org/wp-admin/post.php?post=31211&action=edit

The "Wide Line" should probably work with the full width, wide width, regular options.

Would still love to do something fun with the ideas above but that can wait.

**Comment by laras126** [comment]
@slambert 
> The "Wide Line" should probably work with the full width, wide width, regular options.

Does this mean the Wide Line style should be the same regardless of the width that is set?

Also, should it behave the same if added in a group? e.g. even when it is in a group, it extends the full width of the browser window.

**Comment by slambert** [comment]
No, I think it could be much simpler - make it match what the gutenberg block describes. So the ends of the line extends to the full, wide, or regular width. Know what I mean?

**Comment by slambert** [comment]
I'm gonna change these HRs but... 

https://c4aa.org/advising

<img width="1624" alt="Screen Shot 2022-06-09 at 4 18 46 PM" src="https://user-images.githubusercontent.com/67271/172960792-dfe2341b-bb0c-4383-8844-fe363db52f79.png">

**Comment by slambert** [comment]
I can update this as needed, but the basic idea is the same - more deliberate styling for these separators and hrs.

**Comment by andrewheins** [comment]
Updated to request.

**Comment by slambert** [comment]
Here's the design for the dividers/separators. I'd like the grey to be the default in gutenburg and the red to be an option. @andrewheins going to move this to the todo column in our project.

![Screenshot 2024-01-31 at 10 13 27 AM](https://github.com/thec4aa/c4aa-org/assets/67271/19ea1b21-ab90-4deb-8abd-e02eb0b7d351)

![Screenshot 2024-01-31 at 10 13 36 AM](https://github.com/thec4aa/c4aa-org/assets/67271/921c31bf-54f8-415f-bb7a-03d57c41a694)

**Comment by slambert** [comment]
Pretty sure this is done. Once it's live, we can close this.
