### ISSUE TITLE
style blockquotes

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#45]
Should have 
polygon clip path background shape with a bit of random variation on the corners
a bit of random rotation (-2 +2) degrees
able to overlap elements and have overlap colors darken/multiply (I can explain if this doesn't make sense.

3 Testimonial blocks appear here to experiment with:

/about

We'll reuse some of these styling elements for #31 and #11

**Comment by slambert** [comment]
Made progress on this. 

@zoracreates when we have the rotation/polygon thing worked out we can add it to this.

Really into what's happening with this:
    mix-blend-mode: multiply;

<img width="889" alt="Screen Shot 2019-08-11 at 3 16 08 PM" src="https://user-images.githubusercontent.com/67271/62838713-edd25900-bc4d-11e9-9b2c-bb7c7b0508c7.png">

**Comment by slambert** [comment]
FYI, there are two styles of blockquotes - default (small) and large. Here's a screenshot of what the large looks like also and I threw in some links.

I may revisit the font-weight on this later.

<img width="746" alt="Screen Shot 2019-08-11 at 3 38 23 PM" src="https://user-images.githubusercontent.com/67271/62838739-2f630400-bc4e-11e9-8ef6-01c790eed488.png">

**Comment by slambert** [comment]
By the way, that `mix-blend-mode: multiply;` thing looks great with the red over beige, but over black it's gonna look awful. For the purposes of this selector, I think we're ok, but for using it elsewhere we'll need to think it through and test.

**Comment by zoracreates** [comment]
@slambert what is the difference between this and #82, aside from this one having more detail. Are the block-quotes the same as the testimonial blocks?

**Comment by slambert** [comment]
@zoracreates Yeah, I looks like #82 is a dupe of this.

Note: there are "blockquotes" and "pullquotes". Pull quotes is what I'm using just under the featured image and they are used now and again elsewhere. We can add the clippath effect to Pullquotes also and see how they work. Feel free to make a new ticket if you like.

**Comment by zoracreates** [comment]
Great! I'll closed #82 to avoid confusion.
