### ISSUE TITLE
Lose margin between header and first block

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#47]
Looking to get rid of the beige gap on pages like /training /what-we-do:

<img width="1726" alt="Screen Shot 2019-07-05 at 11 31 04 AM" src="https://user-images.githubusercontent.com/67271/60732817-0b0e5c00-9f19-11e9-961d-f33336604def.png">

I tried do this here: https://github.com/thec4aa/c4aa-org/pull/36

We already have code here that, from what I understand, should do it:

https://github.com/thec4aa/c4aa-org/blob/ea442aa12b24edf692f4f9f240c3fd23729070bc/css/03-generic.css#L64-L65

I've tried finding the right selector but can't seem to manage it.  Weird...

**Comment by laras126** [comment]
Remove margin when there is a quote block first (might need to be a negative marign)

**Comment by laras126** [comment]
Use clip-path to add angle to quote blocks, make it a slightly uneven square, only clippath on bottom for top block, other quote blocks have top and bottom offset

**Comment by slambert** [comment]
Did a quick test on:

/resources

```
.site-header.featured-image {
    margin-bottom: -3rem;
}
```

Worked

Still confused why zero wouldn't do it. But

**Comment by slambert** [comment]
I think @zoracreates got this done right? Closing
