### ISSUE TITLE
Standardize image sizes?

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#5]
I know in the past you'd set some standard image sizes for a theme - thumbnail, medium, large. 

I started using 320px on /about and it's working, but if we're gonna go with that let's make an informed choice, right?

**Comment by slambert** [comment]
I'm rethinking the image sizes on /about. Check out the page.

Toward the bottom I'm using the "Media & Text block" and applying backgrounds. I think it works well (especially if they can be joined together without padding?)

But - the download size of those images may get kinda chunky. It's already 3.5MB and 40% is from the images.

**Comment by laras126** [comment]
The standard sizes in this theme are:
1400 for L
768 for M
580 for S - we could change this to smaller

WP resizes any image to those 3 sizes when you upload it, then in the image blocks it uses `srcset` with all 3 sizes - this allows the browser to decide which image to download according to bandwidth and viewport size. The best approach is to upload the largest size image, and allow WP and the browser to handle the resizing.

Lazy loading the images is the solution for lessening the download size. That will eventually be native to browsers, but at the moment I would recommend adding it to the theme like this: https://macarthur.me/posts/build-your-own-simple-lazy-loading-functionality-in-wordpress

Jetpack has a Lazy Images setting, but AFAIK it does not support srcset which I think is a deal breaker.
