### ISSUE TITLE
Links are blue

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#51]
See home page

Links should be red. One can change it here, but that slider is not so precise:

<img width="368" alt="Screen Shot 2019-07-05 at 2 02 44 PM" src="https://user-images.githubusercontent.com/67271/60738854-bfb27880-9f2d-11e9-8ed6-5f2960aedf14.png">

**Comment by slambert** [comment]
Also noticed this blue showed up in the images on the category archive page

**Comment by laras126** [comment]
I think there is a big set of selectors in one of the stylesheets that overrides them - we can see what's not applying there and add the selector.

**Comment by slambert** [comment]
I think you're right about the big set of the selectors that this is drawing from in Twenty Nineteen.
