### ISSUE TITLE
Set default colors for paragraph block to our colors

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#6]
When using the paragraph block one can choose some colors. It would be great if these were our colors (or shades of those colors)

<img width="1125" alt="Screen Shot 2019-06-08 at 6 16 04 PM" src="https://user-images.githubusercontent.com/67271/59152790-a1825700-8a19-11e9-8739-3d6d996b4499.png">

**Comment by slambert** [comment]
FYI = this same color settings UI comes up in the pullquote block.

**Comment by slambert** [comment]
Ah ha! Here's how:

https://kinsta.com/blog/twenty-nineteen-theme/#block-color-palettes

**Comment by slambert** [comment]
Check my work! @laras126

**Comment by slambert** [comment]
This isn't exactly working yet. Basically trying to get a custom color palette for blocks. The color palette shows up in the backend editor, but not in the front end.

Here's the documentation:
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes

Here's the code I added:
functions.php:
https://github.com/thec4aa/c4aa-org/blob/660de90ae3e2199c0e5c7e70775729c63eb35db5/functions.php#L54-L91

00-settings.css:
https://github.com/thec4aa/c4aa-org/blob/660de90ae3e2199c0e5c7e70775729c63eb35db5/css/00-settings.css#L9-L49

**Comment by laras126** [comment]
Ah, interesting – Gutenberg parses the `c4aa`namespace to `has-c-4-aa-red-background-color`, I guess it doesn't like the number. I removed the `4` in the namespace for now, and am making a note to my future self to open an issue about this with Gutenberg.
