### ISSUE TITLE
hr and separator blocks don't clear both

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#61]
Seems like good practice? Maybe there's a situation where you wouldn't want that – I can be convinced.

From this page:

http://backtobasics.c4aa.org/advising/

<img width="1863" alt="Screen Shot 2019-07-30 at 9 03 55 AM" src="https://user-images.githubusercontent.com/67271/62131636-8c9fa280-b2a9-11e9-9e8e-3f4b0661f04f.png">

**Comment by zoracreates** [comment]
I am a bit confused about this issue. The hr separator blocks are not showing in my master branch. Is this something that has not been committed? I created a pseudo after element as a fix on #68, but I am wondering if you want the hr as a separator.
<img width="731" alt="Screen Shot 2019-08-08 at 5 01 09 PM" src="https://user-images.githubusercontent.com/29125560/62737615-2a0f7a80-b9fe-11e9-98c0-758cd8a0646f.png">

**Comment by slambert** [comment]
Hm, looks like the WordPress database we're working with locally doesn't have those changes. I made some updates you can see on the server: http://backtobasics.c4aa.org/advising/

@laras126 what's the best way for us to get the latest version of the database locally?

**Comment by slambert** [comment]
Lara and I talked. It's simpler just to go into the code editor in WordPress and update the page or two we need this for.

I'll post updated code for the advising page in slack

**Comment by zoracreates** [comment]
Great thanks!
