### ISSUE TITLE
Add clippath effects on blockquotes

### ISSUE THREAD

**Issue by zoracreates** [thec4aa/c4aa-org#82]
Use the heading  (h2, h3, and h4) polygon effect on blockqoutes.

**Comment by slambert** [comment]
Also, while you're in there, could you fix up this? https://github.com/thec4aa/c4aa-org/pull/77#discussion_r313673770

**Comment by zoracreates** [comment]
> Also, while you're in there, could you fix up this? [#77 (comment)](https://github.com/thec4aa/c4aa-org/pull/77#discussion_r313673770)

Fixed!
