### ISSUE TITLE
Style .wp-block-latest-posts

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#86]
@zoracreates - do you mind taking this on? I'm close, but I'm betting you can hunt down the selectors better than I. Also, how do we make sure the default font never appears? 🤔 

Right now this looks like this:

<img width="931" alt="Screen Shot 2019-08-16 at 3 30 42 PM" src="https://user-images.githubusercontent.com/67271/63194317-b09b0c00-c03d-11e9-85a0-28a16a800b76.png">

The default font kicks in, etc.

I want to show excerpts so I had to change some settings in gutenburg (and install the gutenburg plugin so you get the latest stuff)

Here's the settings:

<img width="965" alt="Screen Shot 2019-08-16 at 3 49 55 PM" src="https://user-images.githubusercontent.com/67271/63194384-e2ac6e00-c03d-11e9-9765-1185593361bf.png">

Then you get this:

<img width="1099" alt="Screen Shot 2019-08-16 at 3 44 29 PM" src="https://user-images.githubusercontent.com/67271/63194402-f061f380-c03d-11e9-9c37-c7ec8fcc5ac5.png">

Then I started doing some initial styling (below is my code):

<img width="330" alt="Screen Shot 2019-08-16 at 3 49 44 PM" src="https://user-images.githubusercontent.com/67271/63194441-096aa480-c03e-11e9-8531-e7bad91e7ffc.png">

```
font-family: "roboto_slabregular";
font-size: calc(22px * 1.125);
font-weight: bold;
line-height: 1.2;
padding-bottom: 0.75rem;
text-transform: uppercase;
letter-spacing: .14em;

```

```
color: var ( --color-brandBlack); /* this will change later */
font-family: "roboto_slablight";
font-size: 1em;
```

**Comment by zoracreates** [comment]
@slambert I played a bit with the style for this, but I'm not sure if you had other ideas beyond your comments. This is what I have. Thoughts?
![Screen Shot 2019-09-25 at 7 12 43 PM](https://user-images.githubusercontent.com/29125560/65646282-97846400-dfc8-11e9-80b4-6829c8e25b28.png)
