### ISSUE TITLE
style headers in columns

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#95]
I caught this on the home page:

<img width="1271" alt="Screen Shot 2019-08-23 at 4 27 27 PM" src="https://user-images.githubusercontent.com/67271/63622055-99bb6300-c5c3-11e9-8008-70a1bce37022.png">

The max-width is set to 50%, which is lovely elsewhere, but when in a column block it get goofy.

I tried this:

```
.wp-block-column h3 {

    max-width: max-content;

}
```

Which worked well, but if you make the screen a little smaller it goes goofy again:

<img width="772" alt="Screen Shot 2019-08-23 at 4 31 05 PM" src="https://user-images.githubusercontent.com/67271/63622127-c40d2080-c5c3-11e9-9252-780b2ae3a473.png">

Smaller still and it works because the column takes more width:

<img width="635" alt="Screen Shot 2019-08-23 at 4 31 22 PM" src="https://user-images.githubusercontent.com/67271/63622148-cf604c00-c5c3-11e9-8bc7-71e77a5d4e07.png">

Possible solutions _I_ can think of (maybe you can think of something better):

- some conditional decrease in the size of the font. I found this in the theme code that may be relevant:

```
wp-block-column {
    flex-basis: calc(50% - 16px);
    flex-grow: 0;
}
```

- decrease the font size of the h3 when it's in a column (not loving this).

Any other ideas?

**Comment by zoracreates** [comment]
Is this still an issue or can it be closed? I'm not sure what the invalid label means, but I noticed the columns were removed from here and I am not seeing the issue elsewhere. Let me know if you'd like me to look into it!

**Comment by laras126** [comment]
@slambert can we close this?

**Comment by slambert** [comment]
@laras126 We didn't change any code, so it could come up again. But it does seem like an edge case that can be handled a different way by the author or fixed later with css if necessary. So yeah, let's drop it for now.
